<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.72644"/>
    <xacro:property name="chassis_width" value="0.49784"/>
    <xacro:property name="chassis_height" value="0.38608"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.0762"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    
    <xacro:property name="wheel_offset_x" value="0.18161"/>
    <xacro:property name="wheel_offset_y" value="0.26192"/>
    <xacro:property name="wheel_offset_z" value="0.033"/>
    <xacro:property name="front_wheel_offset_x" value="0.36322"/>
    
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    

    <!-- front left steering -->

    <link name="front_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="front_left_wheel"> 
    <mu1 value="2.0"/> 
    <mu2 value="2.0"/> 
    <kp  value="10000000.0" /> 
    <kd  value="1.0" /> 
    <fdir1 value="0 1 0"/> 
    <material>Gazebo/Blue</material> 
  </gazebo>

    <link name="left_wheel_assembly">
		<collision> 
		  <origin xyz="0 0 0" rpy="0 1.5708 1.5708" />
		  <geometry> 
		   <cylinder length="0.001" radius="0.04"/> 
		  </geometry> 
		</collision> 

		<visual> 
		  <origin xyz="0 0 0" rpy="0 1.5708 1.5708" /> 
		  <geometry> 
			<cylinder length="0.001" radius="0.04"/> 
		  </geometry> 
		  <material name="white"/> 
		</visual> 		

		<xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
	</link>  

  <gazebo reference="left_wheel_assembly"> 
    <mu1 value="2.0"/> 
    <mu2 value="2.0"/> 
    <kp  value="10000000.0" /> 
    <kd  value="1.0" /> 
    <fdir1 value="0 1 0"/> 
    <material>Gazebo/White</material> 
  </gazebo>


    <joint name="left_wheel_hinge" type="revolute"> 
        <parent link="base_link"/> 
        <child link="left_wheel_assembly"/> 
        <origin xyz="${front_wheel_offset_x} ${wheel_offset_y} 0" rpy="0 0 0" />  
        <axis xyz="0 0 -1" rpy="0 0 0" /> 
        <limit effort="100" velocity="1" lower="-1" upper="1"/> 
        <dynamics damping="0.0" friction="0.0"/> 
    </joint> 

    <!-- Front Right Steering Joint -->
    <joint name="front_left_rotate" type="continuous">
        <parent link="left_wheel_assembly"/>
        <child link="front_left_wheel"/>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/> <!-- Rotates around z-axis -->
    </joint>

    <!-- Front Right Wheel -->
    <link name="front_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="front_right_wheel"> 
    <mu1 value="2.0"/> 
    <mu2 value="2.0"/> 
    <kp  value="10000000.0" /> 
    <kd  value="1.0" /> 
    <fdir1 value="0 1 0"/> 
    <material>Gazebo/Blue</material> 
  </gazebo>

    <link name="right_wheel_assembly">
		<collision> 
		  <origin xyz="0 0 0" rpy="0 1.5708 1.5708" />
		  <geometry> 
		   <cylinder length="0.001" radius="0.04"/> 
		  </geometry> 
		</collision> 

		<visual> 
		  <origin xyz="0 0 0" rpy="0 1.5708 1.5708" /> 
		  <geometry> 
			<cylinder length="0.001" radius="0.04"/> 
		  </geometry> 
		  <material name="white"/> 
		</visual> 		

		<xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
	</link>  

  <gazebo reference="right_wheel_assembly"> 
    <mu1 value="2.0"/> 
    <mu2 value="2.0"/> 
    <kp  value="10000000.0" /> 
    <kd  value="1.0" /> 
    <fdir1 value="0 1 0"/> 
    <material>Gazebo/White</material> 
  </gazebo>


    <joint name="right_wheel_hinge" type="revolute"> 
        <parent link="base_link"/> 
        <child link="right_wheel_assembly"/> 
        <origin xyz="${front_wheel_offset_x} -${wheel_offset_y} 0" rpy="0 0 0" />  
        <axis xyz="0 0 1" rpy="0 0 0" /> 
        <limit effort="100" velocity="1" lower="-1" upper="1"/> 
        <dynamics damping="0.0" friction="0.0"/> 
    </joint> 

    <!-- Front Right Steering Joint -->
    <joint name="front_right_rotate" type="continuous">
        <parent link="right_wheel_assembly"/>
        <child link="front_right_wheel"/>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/> <!-- Rotates around z-axis -->
    </joint>

    
    
    <!-- Gazebo Plugin -->
 
    <!-- Physics for Gazebo -->
    
    <gazebo reference="front_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel"> 
        <mu1 value="2.0"/> 
        <mu2 value="2.0"/> 
        <kp  value="10000000.0" /> 
        <kd  value="1.0" /> 
        <fdir1 value="0 1 0"/> 
        <material>Gazebo/Blue</material> 
    </gazebo>


    <!-- RIGHT WHEEL LINK -->

    <joint name="right_rear_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="right_wheel"> 
    <mu1 value="2.0"/> 
    <mu2 value="2.0"/> 
    <kp  value="10000000.0" /> 
    <kd  value="1.0" /> 
    <fdir1 value="0 1 0"/> 
    <material>Gazebo/Blue</material> 
  </gazebo>

</robot>