controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    ack_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

ack_cont:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    rear_wheels_names: [left_rear_wheel_joint, right_rear_wheel_joint]
    front_wheels_names: [left_wheel_hinge, right_wheel_hinge]

    front_wheel_track: 0.36322
    rear_wheel_track: 0.36322
    wheelbase: 0.49784
    front_wheels_radius: 0.076
    rear_wheels_radius: 0.076
    use_stamped_vel: true #stmaped

